NR_ACTIVE_CONNECTIONS = 10
NR_MAX_LINKS = 11
STATE_SIZE = NR_ACTIVE_CONNECTIONS * 2 + NR_MAX_LINKS + 2
#NUMBER_OF_HOSTS = 13
NUMBER_OF_PATHS = 3
#NUMBER_OF_AGENTS = 25

NR_EPOCHS = 25     #epoch
EPOCH_SIZE = 100    #episode

NOTES = "STATE_SIZE = NUMBER_OF_AGENTS * NUMBER_OF_AGENTS * NR_MAX_LINKS * 1"

GNN_MODULE = False

PATH_SIMULATION = "student"
#PATH_SIMULATION = "server2/Thesis"
SIM_NR = 0

### NETWORK TOPOLOGY TYPE ###
#TOPOLOGY_TYPE = "service_provider"; NUMBER_OF_HOSTS = 65; NUMBER_OF_AGENTS = 65
#TOPOLOGY_TYPE = "small_network"; NUMBER_OF_HOSTS = 25; NUMBER_OF_AGENTS = 25
TOPOLOGY_TYPE = "arpanet"; NUMBER_OF_HOSTS = 33; NUMBER_OF_AGENTS = 33

#STATE_SIZE = NUMBER_OF_AGENTS * NUMBER_OF_AGENTS * NR_MAX_LINKS * 1

### TRAIN COMBINATIONS ###
#1 
CRITIC_DOMAIN = "central_critic"; NEURAL_NETWORK = "duelling_q_network"
#2
#CRITIC_DOMAIN = "central_critic"; NEURAL_NETWORK = "simple_q_network"
#3
#CRITIC_DOMAIN = "local_critic"; NEURAL_NETWORK = "duelling_q_network"

GRAPH_BATCH_SIZE = 3 #batch size for graph

EVALUATE = False; UPDATE_WEIGHTS = False
#EVALUATE = True; UPDATE_WEIGHTS = False
#EVALUATE = True; UPDATE_WEIGHTS = True

### Modified Network In Evaluate  ###
MODIFIED_NETWORK = "edges"
#MODIFIED_NETWORK = "intranet"
